# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.bridge import kiwoom_pb2 as kiwoom__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kiwoom_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KiwoomServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/kiwoom.KiwoomService/Login',
                request_serializer=kiwoom__pb2.LoginRequest.SerializeToString,
                response_deserializer=kiwoom__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.GetStockPrice = channel.unary_unary(
                '/kiwoom.KiwoomService/GetStockPrice',
                request_serializer=kiwoom__pb2.StockPriceRequest.SerializeToString,
                response_deserializer=kiwoom__pb2.StockPriceResponse.FromString,
                _registered_method=True)
        self.SendOrder = channel.unary_unary(
                '/kiwoom.KiwoomService/SendOrder',
                request_serializer=kiwoom__pb2.OrderRequest.SerializeToString,
                response_deserializer=kiwoom__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/kiwoom.KiwoomService/GetBalance',
                request_serializer=kiwoom__pb2.BalanceRequest.SerializeToString,
                response_deserializer=kiwoom__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.RegisterRealtime = channel.unary_unary(
                '/kiwoom.KiwoomService/RegisterRealtime',
                request_serializer=kiwoom__pb2.RealtimeRequest.SerializeToString,
                response_deserializer=kiwoom__pb2.RealtimeResponse.FromString,
                _registered_method=True)


class KiwoomServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterRealtime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KiwoomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=kiwoom__pb2.LoginRequest.FromString,
                    response_serializer=kiwoom__pb2.LoginResponse.SerializeToString,
            ),
            'GetStockPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockPrice,
                    request_deserializer=kiwoom__pb2.StockPriceRequest.FromString,
                    response_serializer=kiwoom__pb2.StockPriceResponse.SerializeToString,
            ),
            'SendOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrder,
                    request_deserializer=kiwoom__pb2.OrderRequest.FromString,
                    response_serializer=kiwoom__pb2.OrderResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=kiwoom__pb2.BalanceRequest.FromString,
                    response_serializer=kiwoom__pb2.BalanceResponse.SerializeToString,
            ),
            'RegisterRealtime': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRealtime,
                    request_deserializer=kiwoom__pb2.RealtimeRequest.FromString,
                    response_serializer=kiwoom__pb2.RealtimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiwoom.KiwoomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiwoom.KiwoomService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KiwoomService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiwoom.KiwoomService/Login',
            kiwoom__pb2.LoginRequest.SerializeToString,
            kiwoom__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiwoom.KiwoomService/GetStockPrice',
            kiwoom__pb2.StockPriceRequest.SerializeToString,
            kiwoom__pb2.StockPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiwoom.KiwoomService/SendOrder',
            kiwoom__pb2.OrderRequest.SerializeToString,
            kiwoom__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiwoom.KiwoomService/GetBalance',
            kiwoom__pb2.BalanceRequest.SerializeToString,
            kiwoom__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterRealtime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiwoom.KiwoomService/RegisterRealtime',
            kiwoom__pb2.RealtimeRequest.SerializeToString,
            kiwoom__pb2.RealtimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
